server:
  port: ${auth_port}

spring:
  rabbitmq:
    host: ${rabbitmq_host}
    port: ${rabbitmq_port}
    username: ${rabbitmq_username}
    password: ${rabbitmq_password}
  zipkin:
    base-url: ${zipkin_url}
    enabled: true
    service:
      name: auth-service
  security:
    user:
      name: B!lgeAdamKu!!anicisi
  datasource:
    url: ${db_postgresql_url}
    username: ${db_postgresql_username}
    password: ${db_postgresql_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

raceapplication:
  url:
    auth: ${auth_url}
    main: ${main_url}
    user: ${user_url}