server:
  port: 9090

spring:
  security:
    user:
      name: mehmet
      password: 123456
  datasource:
    url: 'jdbc:postgresql://localhost:5432/YarismaProjesi'
    username: 'postgres'
    password: 'Nic3993.'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true




raceapplication:
  url:
    auth: http://localhost:9090/
    main: http://localhost:9091/
    user: http://localhost:9092/