server:
  port: ${main_port}

spring:
  zipkin:
    base-url: ${zipkin_url}
    enabled: true
    service:
      name: main-service
  datasource:
    url: ${db_postgresql_url}
    username: ${db_postgresql_username}
    password: ${db_postgresql_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

raceapplication:
  url:
    auth: ${auth_url}
    main: ${main_url}
    user: ${user_url}