server:
  port: ${user_port}

spring:
  rabbitmq:
    host: ${rabbitmq_host}
    port: ${rabbitmq_port}
    username: ${rabbitmq_username}
    password: ${rabbitmq_password}
  zipkin:
    base-url: ${zipkin_url}
    enabled: true
    service:
      name: user-service
  redis:
    host: ${redis_host}
    port: ${redis_port}
  data:
    mongodb:
      host: ${db_mongo_url}
      port: ${db_mongo_port}
      database: ${db_mongo_database }
      username: ${db_mongo_username}
      password: ${db_mongo_password}

raceapplication:
  url:
    auth: ${auth_url}
    main: ${main_url}
    user: ${user_url}