server:
  port: 9092

logging:
  level:
    root: info
    #    org.mehmet: debug
    #    org.springframework: info
    #    org.hibernate: info
  file:
    name: user-service-application.log
    max-size: 1MB

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: muhammet
    password: Aa123456*
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    service:
      name: user-service
  datasource:
    url: 'jdbc:postgresql://localhost:5432/YarismaProjesi'
    username: 'postgres'
    password: 'Nic3993.'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

raceapplication:
  url:
    auth: http://localhost:9090/
    main: http://localhost:9091/
    user: http://localhost:9092/