server:
  port: 9092

logging:
  level:
    root: info
    #    org.mehmet: debug
    #    org.springframework: info
    #    org.hibernate: info
  file:
    name: user-service-application.log
    max-size: 1MB

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: mehmet
    password: Aa123456*
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    service:
      name: user-service
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      host: 34.170.152.48
      port: 19589
      database: bilgeyarisma
      username: bilgeadamuser
      password: '147896325Mm.'

raceapplication:
  url:
    auth: http://localhost:9090/
    main: http://localhost:9091/
    user: http://localhost:9092/