server:
  port: 9092

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/YarismaMainDB'
    username: 'postgres'
    password: 'Nic3993.'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

raceapplication:
  url:
    auth: http://localhost:9090/auth-service/
    main: http://localhost:9090/main-service/
    user: http://localhost:9090/user-service/