apiVersion: v1
kind: Secret
metadata:
  name: yarismasecret
type: Opaque
stringData:
  db_postgresql_username: 'postgres'
  db_postgresql_password: 'Nic3993.'
  db_postgresql_url: 'jdbc:postgresql://10.64.1.11:5432/YarismaDB'
  db_mongo_username: 'AdminBilgeadam'
  db_mongo_password: '147896325Mm.'
  db_mongo_url: '10.64.1.47'
  db_mongo_port: '27017'
  db_mongo_database: 'bilgeyarisma'
  services_auth_clusterip: '10.68.4.139'
  services_main_clusterip: '10.68.7.101'
  services_user_clusterip: '10.68.0.160'
  services_configserver_clusterip: '10.68.8.164'
  services_elastic_clusterip: '10.68.14.100'
  elastic_search_url: 'http://10.64.1.53:9200'
  redis_host: '10.64.1.52'
  redis_port: '6379'
  rabbitmq_host: '10.64.1.46'
  rabbitmq_port: '5672'
  rabbitmq_username: 'bilgeuser'
  rabbitmq_password: 'B!lge123*'
  zipkin_url: 'http://10.64.1.44:9411'
  auth_port: '9090'
  main_port: '9091'
  user_port: '9092'
  configserver_port: '8888'
  elastic_port: '9099'
  auth_url: 'http://10.68.4.139:9090/'
  main_url: 'http://10.68.7.101:9091/'
  user_url: 'http://10.68.0.160:9092/'
  gateway_auth_url: 'http://10.68.4.139:9090'
  gateway_main_url: 'http://10.68.7.101:9091'
  gateway_user_url: 'http://10.68.0.160:9092'
  config_server_url: 'http://10.68.8.164:8888'