apiVersion: v1
kind: Secret
metadata:
  name: yarismasecret
type: Opaque
stringData:
  db_username: 'postgres'
  db_password: 'Nic3993.'
  db_url: 'jdbc:postgresql://10.64.1.11:5432/YarismaDB'
  services_auth_clusterip: '10.68.4.139'
  services_main_clusterip: '10.68.7.101'
  services_user_clusterip: '10.68.0.160'
  auth_port: '9090'
  main_port: '9091'
  user_port: '9092'
  auth_url: 'http://10.68.4.139:9090/'
  main_url: 'http://10.68.7.101:9091/'
  user_url: 'http://10.68.0.160:9092/'
  gateway_auth_url: 'http://10.68.4.139:9090'
  gateway_main_url: 'http://10.68.7.101:9091'
  gateway_user_url: 'http://10.68.0.160:9092'
  config_server_url: 'http://10.64.1.17:8888'